[package]
name = "pretty_ini"
version = "0.1.4.1"
edition = "2021"
description = "Light library to read/write ini files"
license = "MIT"
readme = "README.md"
keywords = ["ini", "file"]
repository = "https://github.com/eVisualUser/pretty-ini"

[dependencies]
